"""Federation — multi-node SQLite replication via Litestream.

Generates and manages Litestream replication configuration for the Jarvis homelab.
Litestream continuously replicates SQLite WAL changes to remote replicas, enabling:

  - Zero-RPO replication between homelab nodes
  - Point-in-time restore from S3/SFTP/GCS replica
  - Read replicas on secondary nodes (192.168.111.27, .28, .29)
  - Disaster recovery without downtime

Homelab nodes (from ROADMAP.md hardware plan):
  Primary  — current machine (main FastAPI + Ollama server)
  EliteBook — 192.168.111.28 (16GB) — initial Jarvis brain, forge agents
  Mini PC  — 192.168.111.27  (8GB)  — worker node
  EVO-X2 A — 192.168.111.20  (128GB) — training node
  EVO-X2 B — 192.168.111.21  (128GB) — redundancy

Replica destinations:
  FORGE_REPLICA_DIR  — local SFTP replica dir (default: /data/jarvis-replicas)
  FORGE_S3_BUCKET    — S3 bucket for off-site backup (optional)
  FORGE_REPLICA_HOSTS — colon-separated SSH hosts for SFTP replication
"""
from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml  # type: ignore[import-untyped]

logger = logging.getLogger(__name__)

# Databases to replicate (relative to Jarvis root)
_DATABASES = [
    "data/memory.db",
    "data/decisions.db",
    "data/episodes.db",
    "data/semantic.db",
    "data/forge.db",
    "data/bitemporal.db",
    "data/project_inventory.db",
    "data/knowledge_lake.db",
    "data/lora_jobs.db",
]

_HOMELAB_NODES = {
    "elitebook": "192.168.111.28",
    "mini_pc":   "192.168.111.27",
    "evo_x2_a":  "192.168.111.20",
    "evo_x2_b":  "192.168.111.21",
}

_LITESTREAM_TEMPLATE = """\
# Litestream configuration — auto-generated by Jarvis Federation
# Run with: litestream replicate -config {config_path}
# Restore: litestream restore -config {config_path} -replica <replica_name> /path/to/restore.db

access-key-id: $LITESTREAM_ACCESS_KEY_ID
secret-access-key: $LITESTREAM_SECRET_ACCESS_KEY

dbs:
{db_sections}
"""

_DB_SECTION_TEMPLATE = """\
  - path: {db_path}
    replicas:
{replica_sections}
"""

_SFTP_REPLICA_TEMPLATE = """\
      - name: {name}
        type: sftp
        host: {host}:22
        user: ${{LITESTREAM_SFTP_USER:-praxisforma}}
        key-path: ${{LITESTREAM_KEY_PATH:-~/.ssh/id_ed25519}}
        path: {remote_path}/{db_name}
        sync-interval: 10s
        snapshot-interval: 1h
        retention: 24h
"""

_S3_REPLICA_TEMPLATE = """\
      - name: s3-backup
        type: s3
        bucket: {bucket}
        path: jarvis/{db_name}
        region: ${{AWS_REGION:-us-east-1}}
        sync-interval: 30s
        snapshot-interval: 6h
        retention: 72h
"""

_LOCAL_REPLICA_TEMPLATE = """\
      - name: local-{index}
        type: file
        path: {replica_dir}/{db_name}
        sync-interval: 5s
        snapshot-interval: 1h
        retention: 24h
"""

_RESTORE_SCRIPT = """\
#!/bin/bash
# Litestream restore script — generated by Jarvis Federation
# Run this on a new node to restore all databases from replicas
set -e

CONFIG={config_path}
JARVIS_ROOT={jarvis_root}

echo "[Federation] Starting Jarvis database restore..."

{restore_commands}

echo "[Federation] All databases restored successfully."
echo "  Start Jarvis with: python server.py"
"""

_SYSTEMD_UNIT = """\
[Unit]
Description=Litestream SQLite Replication for Jarvis
After=network.target
Requires=network.target

[Service]
Type=simple
User=praxisforma
EnvironmentFile={env_file}
ExecStart=/usr/local/bin/litestream replicate -config {config_path}
Restart=always
RestartSec=5

[Install]
WantedBy=multi-user.target
"""


@dataclass
class FederationConfig:
    """Generated federation configuration."""
    config_path: str
    databases: list[str]
    replica_hosts: list[str]
    s3_bucket: str | None
    local_replica_dir: str | None
    restore_script_path: str
    systemd_unit_path: str


class FederationManager:
    """Generates and manages Litestream replication config for the Jarvis homelab.

    Usage::

        fm = FederationManager()

        # Generate config for all databases to replicate to homelab nodes
        config = fm.generate(output_dir="/etc/litestream")
        print(config.config_path)

        # Get install instructions
        print(fm.install_instructions())

        # Add a new replica node
        fm.add_node("new_pc", "192.168.111.30")
    """

    def __init__(
        self,
        jarvis_root: str | None = None,
        replica_hosts: list[str] | None = None,
        s3_bucket: str | None = None,
        local_replica_dir: str | None = None,
    ):
        self._root = jarvis_root or str(Path(__file__).parent.parent.parent)
        env_hosts_raw = os.getenv("FORGE_REPLICA_HOSTS", "")
        env_hosts = [h.strip() for h in env_hosts_raw.split(":") if h.strip()]
        self._replica_hosts = replica_hosts or env_hosts or list(_HOMELAB_NODES.values())[:2]
        self._s3_bucket = s3_bucket or os.getenv("FORGE_S3_BUCKET")
        self._local_dir = local_replica_dir or os.getenv("FORGE_REPLICA_DIR")
        self._extra_nodes: dict[str, str] = {}

    def add_node(self, name: str, host: str) -> None:
        """Add an additional replica node."""
        self._extra_nodes[name] = host
        if host not in self._replica_hosts:
            self._replica_hosts.append(host)

    def generate(self, output_dir: str = "/etc/litestream") -> FederationConfig:
        """Generate all Litestream config files.

        Args:
            output_dir: Directory to write config files into.

        Returns:
            FederationConfig describing what was written.
        """
        Path(output_dir).mkdir(parents=True, exist_ok=True)

        config_path = str(Path(output_dir) / "litestream.yml")
        restore_path = str(Path(output_dir) / "restore.sh")
        systemd_path = str(Path(output_dir) / "litestream.service")
        env_path = str(Path(output_dir) / "litestream.env")

        db_sections = self._build_db_sections()
        config_content = _LITESTREAM_TEMPLATE.format(
            config_path=config_path,
            db_sections=db_sections,
        )

        with open(config_path, "w") as f:
            f.write(config_content)

        restore_content = self._build_restore_script(config_path)
        with open(restore_path, "w") as f:
            f.write(restore_content)
        Path(restore_path).chmod(0o755)

        systemd_content = _SYSTEMD_UNIT.format(
            config_path=config_path,
            env_file=env_path,
        )
        with open(systemd_path, "w") as f:
            f.write(systemd_content)

        env_content = self._build_env_file()
        with open(env_path, "w") as f:
            f.write(env_content)

        logger.info(
            "Federation: generated config at %s (%d DBs, %d hosts)",
            config_path, len(_DATABASES), len(self._replica_hosts),
        )

        return FederationConfig(
            config_path=config_path,
            databases=_DATABASES,
            replica_hosts=list(self._replica_hosts),
            s3_bucket=self._s3_bucket,
            local_replica_dir=self._local_dir,
            restore_script_path=restore_path,
            systemd_unit_path=systemd_path,
        )

    def generate_node_config(
        self,
        node_name: str,
        output_dir: str = "/etc/litestream",
    ) -> str:
        """Generate a replica-specific config for a node (no primary replication).

        This config just restores from replicas and stays in sync (read-only replica).
        """
        Path(output_dir).mkdir(parents=True, exist_ok=True)
        config_path = str(Path(output_dir) / f"litestream-{node_name}.yml")

        # Simplified read-replica config
        db_entries = []
        for db in _DATABASES:
            abs_path = str(Path(self._root) / db)
            db_name = Path(db).name
            entry = {
                "path": abs_path,
                "replicas": [
                    {
                        "name": "source",
                        "type": "sftp",
                        "host": f"{self._replica_hosts[0]}:22",
                        "user": "${LITESTREAM_SFTP_USER:-praxisforma}",
                        "key-path": "${LITESTREAM_KEY_PATH:-~/.ssh/id_ed25519}",
                        "path": f"/data/jarvis-replicas/{db_name}",
                    }
                ],
            }
            db_entries.append(entry)

        config = {"dbs": db_entries}
        with open(config_path, "w") as f:
            yaml.dump(config, f, default_flow_style=False, sort_keys=False)

        return config_path

    def install_instructions(self) -> str:
        """Return step-by-step installation instructions for Litestream."""
        nodes_str = "\n".join(f"  - {h}" for h in self._replica_hosts)
        return f"""\
=== Jarvis Federation — Litestream Installation ===

1. Install Litestream on ALL nodes:
   curl -fsSL https://github.com/benbjohnson/litestream/releases/latest/download/litestream-linux-amd64.tar.gz | tar xz
   sudo mv litestream /usr/local/bin/

2. Configure SSH keys (run on primary):
   ssh-keygen -t ed25519 -f ~/.ssh/jarvis_replication
   # Copy to each replica host:
{nodes_str}
   ssh-copy-id -i ~/.ssh/jarvis_replication.pub praxisforma@<each-host>

3. Generate configs:
   python -c "from jarvis.forge.federation import FederationManager; FederationManager().generate()"

4. Install systemd service (on primary):
   sudo cp /etc/litestream/litestream.service /etc/systemd/system/
   sudo systemctl daemon-reload
   sudo systemctl enable --now litestream

5. Restore on a new node:
   bash /etc/litestream/restore.sh

6. Verify replication:
   litestream snapshots -config /etc/litestream/litestream.yml

S3 backup: Set FORGE_S3_BUCKET env var before generating config.
"""

    def node_status(self) -> dict[str, Any]:
        """Return replication status — which nodes are reachable."""
        import socket
        status: dict[str, Any] = {}
        for host in self._replica_hosts:
            try:
                socket.setdefaulttimeout(2)
                socket.socket(socket.AF_INET, socket.SOCK_STREAM).connect((host, 22))
                status[host] = "reachable"
            except Exception:
                status[host] = "unreachable"
        return {"nodes": status, "total": len(self._replica_hosts)}

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _build_db_sections(self) -> str:
        sections = []
        for db in _DATABASES:
            abs_path = str(Path(self._root) / db)
            db_name = Path(db).name
            replica_sections = self._build_replica_sections(db_name)
            sections.append(_DB_SECTION_TEMPLATE.format(
                db_path=abs_path,
                replica_sections=replica_sections,
            ))
        return "".join(sections)

    def _build_replica_sections(self, db_name: str) -> str:
        sections = []

        # SFTP replicas to homelab nodes
        for i, host in enumerate(self._replica_hosts):
            name = f"node-{i}"
            for alias, ip in {**_HOMELAB_NODES, **self._extra_nodes}.items():
                if ip == host:
                    name = alias
                    break
            remote_path = "/data/jarvis-replicas"
            sections.append(_SFTP_REPLICA_TEMPLATE.format(
                name=name,
                host=host,
                remote_path=remote_path,
                db_name=db_name,
            ))

        # S3 backup (optional)
        if self._s3_bucket:
            sections.append(_S3_REPLICA_TEMPLATE.format(
                bucket=self._s3_bucket,
                db_name=db_name,
            ))

        # Local file replica (optional)
        if self._local_dir:
            sections.append(_LOCAL_REPLICA_TEMPLATE.format(
                index=0,
                replica_dir=self._local_dir,
                db_name=db_name,
            ))

        return "".join(sections)

    def _build_restore_script(self, config_path: str) -> str:
        restore_commands = []
        for db in _DATABASES:
            abs_path = str(Path(self._root) / db)
            db_dir = str(Path(abs_path).parent)
            restore_commands.append(
                f'mkdir -p {db_dir}\n'
                f'litestream restore -config "{config_path}"'
                f' -replica node-0 -if-db-not-exists "{abs_path}"'
            )
        return _RESTORE_SCRIPT.format(
            config_path=config_path,
            jarvis_root=self._root,
            restore_commands="\n\n".join(restore_commands),
        )

    def _build_env_file(self) -> str:
        return """\
# Litestream environment variables
# Fill in before starting the service
LITESTREAM_ACCESS_KEY_ID=
LITESTREAM_SECRET_ACCESS_KEY=
LITESTREAM_SFTP_USER=praxisforma
LITESTREAM_KEY_PATH=/home/praxisforma/.ssh/id_ed25519
AWS_REGION=us-east-1
"""
