"""LoraRunner — QLoRA fine-tuning job configuration and launcher.

Manages the full lifecycle of a LoRA/QLoRA training job on local hardware:

  1. CONFIG  — generate a training config (YAML + shell script)
  2. PREPARE — verify data, tokenizer, base model availability
  3. LAUNCH  — start the training process (subprocess or remote SSH)
  4. MONITOR — tail logs, report loss curves, detect convergence
  5. PUBLISH — copy adapter to Ollama's model directory for serving

Supported backends:
  - llama.cpp (gguf fine-tuning via llama-finetune)
  - axolotl    (HuggingFace QLoRA trainer)
  - unsloth    (fast QLoRA for AMD/CUDA)
  - mlx-lm    (Apple Silicon MLX)

Hardware targets (from homelab):
  FORGE_TRAIN_HOST   — SSH host for training (default: 192.168.111.27)
  FORGE_TRAIN_GPU    — GPU hours budget per job (default: local)
  FORGE_BASE_MODEL   — HuggingFace model ID to fine-tune (default: Qwen/Qwen2.5-0.5B)

Job state is persisted in data/lora_jobs.db for monitoring and resumption.
"""
from __future__ import annotations

import json
import logging
import os
import shutil
import sqlite3
import subprocess
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

_JOBS_DB = os.path.join(os.path.dirname(__file__), "..", "..", "data", "lora_jobs.db")
_CONFIGS_DIR = os.path.join(os.path.dirname(__file__), "..", "..", "data", "lora_configs")

_DDL = """
CREATE TABLE IF NOT EXISTS lora_jobs (
    id              TEXT PRIMARY KEY,
    name            TEXT NOT NULL,
    base_model      TEXT NOT NULL,
    backend         TEXT NOT NULL,
    data_path       TEXT NOT NULL,
    config_path     TEXT,
    adapter_path    TEXT,
    status          TEXT DEFAULT 'pending',
    created_at      TEXT,
    started_at      TEXT,
    completed_at    TEXT,
    final_loss      REAL,
    epochs_done     INTEGER DEFAULT 0,
    error           TEXT,
    config_json     TEXT
);
"""

# Default QLoRA hyperparameters
_DEFAULT_HPARAMS: dict[str, Any] = {
    "max_seq_length":   2048,
    "per_device_train_batch_size": 2,
    "gradient_accumulation_steps": 4,
    "num_train_epochs": 3,
    "learning_rate":    2e-4,
    "lora_r":           16,
    "lora_alpha":       32,
    "lora_dropout":     0.05,
    "warmup_steps":     10,
    "fp16":             False,
    "bf16":             True,
    "use_4bit":         True,   # QLoRA (4-bit quantization)
    "bnb_4bit_quant_type": "nf4",
    "use_nested_quant":    True,
    "output_logging_steps": 10,
    "save_steps":       100,
}

_AXOLOTL_TEMPLATE = """\
# Auto-generated by Jarvis LoraRunner — {timestamp}
base_model: {base_model}
model_type: AutoModelForCausalLM
tokenizer_type: AutoTokenizer

load_in_4bit: {use_4bit}
strict: false

datasets:
  - path: {data_path}
    type: {dataset_type}

dataset_prepared_path: null
val_set_size: 0.02
output_dir: {output_dir}

sequence_len: {max_seq_length}
sample_packing: false
pad_to_sequence_len: true

adapter: lora
lora_r: {lora_r}
lora_alpha: {lora_alpha}
lora_dropout: {lora_dropout}
lora_target_linear: true

gradient_accumulation_steps: {gradient_accumulation_steps}
micro_batch_size: {per_device_train_batch_size}
num_epochs: {num_train_epochs}
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: {learning_rate}
train_on_inputs: false
group_by_length: false
bf16: {bf16}
fp16: {fp16}
tf32: false

warmup_steps: {warmup_steps}
evals_per_epoch: 2
saves_per_epoch: 1
eval_table_size: 5
logging_steps: {output_logging_steps}

special_tokens:
  pad_token: "<|endoftext|>"
"""


@dataclass
class LoraJob:
    """Represents one fine-tuning job."""
    id: str
    name: str
    base_model: str
    backend: str
    data_path: str
    status: str = "pending"
    config_path: str = ""
    adapter_path: str = ""
    created_at: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    started_at: str | None = None
    completed_at: str | None = None
    final_loss: float | None = None
    epochs_done: int = 0
    error: str | None = None
    config: dict = field(default_factory=dict)


@dataclass
class JobResult:
    """Result of running/monitoring a job."""
    job_id: str
    status: str       # pending | running | completed | failed
    final_loss: float | None
    adapter_path: str
    log_tail: list[str] = field(default_factory=list)
    error: str | None = None


class LoraRunner:
    """Configures, launches, and monitors QLoRA fine-tuning jobs.

    Usage::

        runner = LoraRunner()

        # Create and configure a new job
        job = runner.create_job(
            name="jarvis-critic-v1",
            data_path="/path/to/training_data.jsonl",
            format="sharegpt",
            backend="axolotl",
        )

        # Generate config files (does not start training)
        config_path = runner.configure(job.id)

        # Launch training (returns immediately; use monitor() to track)
        runner.launch(job.id)

        # Check status
        result = runner.monitor(job.id)
        print(result.status, result.final_loss)
    """

    def __init__(self, db_path: str | None = None, configs_dir: str | None = None):
        self._db = db_path or _JOBS_DB
        self._configs_dir = configs_dir or _CONFIGS_DIR
        os.makedirs(os.path.dirname(self._db), exist_ok=True)
        os.makedirs(self._configs_dir, exist_ok=True)
        self._init_db()

    # ------------------------------------------------------------------
    # Job lifecycle
    # ------------------------------------------------------------------

    def create_job(
        self,
        name: str,
        data_path: str,
        base_model: str | None = None,
        backend: str = "axolotl",
        format: str = "sharegpt",
        hparams: dict | None = None,
    ) -> LoraJob:
        """Create and persist a new training job.

        Args:
            name:        Human-readable job name.
            data_path:   Path to training data JSONL file.
            base_model:  HuggingFace model ID (default from FORGE_BASE_MODEL env).
            backend:     Training backend: axolotl | llama.cpp | unsloth | mlx-lm
            format:      Dataset format: sharegpt | dpo | alpaca
            hparams:     Hyperparameter overrides.

        Returns:
            LoraJob — persisted in DB.
        """
        model = base_model or os.getenv("FORGE_BASE_MODEL", "Qwen/Qwen2.5-0.5B")
        cfg = {**_DEFAULT_HPARAMS, **(hparams or {}), "dataset_type": format}
        job = LoraJob(
            id=str(uuid.uuid4()),
            name=name,
            base_model=model,
            backend=backend,
            data_path=data_path,
            config=cfg,
        )
        self._save_job(job)
        logger.info("LoraRunner: created job %s (backend=%s model=%s)", job.id, backend, model)
        return job

    def configure(self, job_id: str) -> str:
        """Generate training config file(s) for the job.

        Returns:
            Path to the generated config file.
        """
        job = self.get_job(job_id)
        if not job:
            raise ValueError(f"Job not found: {job_id}")

        config_dir = Path(self._configs_dir) / job.id
        config_dir.mkdir(exist_ok=True)
        output_dir = config_dir / "output"
        output_dir.mkdir(exist_ok=True)

        if job.backend == "axolotl":
            config_path = self._write_axolotl_config(job, config_dir, output_dir)
        elif job.backend == "llama.cpp":
            config_path = self._write_llamacpp_script(job, config_dir, output_dir)
        else:
            config_path = self._write_generic_config(job, config_dir, output_dir)

        # Persist config path
        conn = self._open()
        conn.execute(
            "UPDATE lora_jobs SET config_path = ?, config_json = ? WHERE id = ?",
            (str(config_path), json.dumps(job.config), job_id),
        )
        conn.commit()
        conn.close()

        logger.info("LoraRunner: config written to %s", config_path)
        return str(config_path)

    def launch(self, job_id: str, remote_host: str | None = None, dry_run: bool = False) -> str:
        """Launch training for the job.

        Args:
            job_id:      Job to launch.
            remote_host: SSH host to run on (None = local).
            dry_run:     If True, print the command but don't execute.

        Returns:
            "launched" | "dry_run" | error message
        """
        job = self.get_job(job_id)
        if not job:
            raise ValueError(f"Job not found: {job_id}")
        if not job.config_path:
            self.configure(job_id)
            job = self.get_job(job_id)

        cmd = self._build_launch_command(job, remote_host)

        if dry_run:
            logger.info("LoraRunner [DRY RUN]: %s", " ".join(cmd))
            return "dry_run"

        try:
            log_path = Path(self._configs_dir) / job_id / "train.log"
            with open(log_path, "w") as log_file:
                proc = subprocess.Popen(
                    cmd,
                    stdout=log_file,
                    stderr=subprocess.STDOUT,
                    text=True,
                )
            # Update job status
            now = datetime.now(timezone.utc).isoformat()
            conn = self._open()
            conn.execute(
                "UPDATE lora_jobs SET status = 'running', started_at = ? WHERE id = ?",
                (now, job_id),
            )
            conn.commit()
            conn.close()
            logger.info("LoraRunner: launched job %s PID=%s", job_id, proc.pid)
            return "launched"
        except FileNotFoundError as exc:
            err = f"Training binary not found: {exc}"
            self._set_error(job_id, err)
            logger.error("LoraRunner: %s", err)
            return err
        except Exception as exc:
            err = str(exc)
            self._set_error(job_id, err)
            return err

    def monitor(self, job_id: str, tail_lines: int = 20) -> JobResult:
        """Check job status, return log tail and metrics.

        Args:
            job_id:     Job to monitor.
            tail_lines: How many log lines to include in result.

        Returns:
            JobResult with status, loss (if available), and log tail.
        """
        job = self.get_job(job_id)
        if not job:
            return JobResult(job_id=job_id, status="not_found", final_loss=None, adapter_path="")

        log_path = Path(self._configs_dir) / job_id / "train.log"
        log_tail: list[str] = []
        final_loss: float | None = job.final_loss

        if log_path.exists():
            try:
                lines = log_path.read_text(errors="ignore").splitlines()
                log_tail = lines[-tail_lines:]
                # Try to parse loss from log
                for line in reversed(lines[-50:]):
                    if "loss" in line.lower():
                        import re
                        m = re.search(r"loss[:\s=]+([0-9.]+)", line, re.IGNORECASE)
                        if m:
                            try:
                                final_loss = float(m.group(1))
                            except ValueError:
                                pass
                        break
            except Exception:
                pass

        # Check if output adapter exists (signals completion)
        adapter_dir = Path(self._configs_dir) / job_id / "output"
        adapter_path = ""
        if adapter_dir.exists():
            # Look for adapter_model.bin or adapter_config.json
            for fname in ("adapter_model.bin", "adapter_model.safetensors", "adapter_config.json"):
                if (adapter_dir / fname).exists():
                    adapter_path = str(adapter_dir)
                    # Mark completed if we weren't already
                    if job.status == "running":
                        self._set_completed(job_id, final_loss, adapter_path)
                        job.status = "completed"
                    break

        return JobResult(
            job_id=job_id,
            status=job.status,
            final_loss=final_loss,
            adapter_path=adapter_path,
            log_tail=log_tail,
            error=job.error,
        )

    def publish_to_ollama(self, job_id: str, model_name: str) -> str:
        """Copy a completed adapter into Ollama's model directory.

        Creates a Modelfile pointing at the adapter and runs `ollama create`.

        Returns:
            "published" | error message
        """
        result = self.monitor(job_id)
        if result.status != "completed":
            return f"Job {job_id} not completed (status={result.status})"
        if not result.adapter_path:
            return "No adapter found"

        job = self.get_job(job_id)
        modelfile_content = (
            f"FROM {job.base_model}\n"
            f"ADAPTER {result.adapter_path}\n"
        )
        modelfile_path = Path(self._configs_dir) / job_id / "Modelfile"
        modelfile_path.write_text(modelfile_content)

        try:
            subprocess.run(
                ["ollama", "create", model_name, "-f", str(modelfile_path)],
                capture_output=True, text=True, timeout=300, check=True,
            )
            logger.info("LoraRunner: published %s to Ollama as '%s'", job_id, model_name)
            return "published"
        except FileNotFoundError:
            return "ollama CLI not found"
        except subprocess.CalledProcessError as exc:
            return f"ollama create failed: {exc.stderr}"

    # ------------------------------------------------------------------
    # Query interface
    # ------------------------------------------------------------------

    def get_job(self, job_id: str) -> LoraJob | None:
        conn = self._open()
        row = conn.execute("SELECT * FROM lora_jobs WHERE id = ?", (job_id,)).fetchone()
        conn.close()
        if not row:
            return None
        return self._row_to_job(dict(row))

    def list_jobs(self, status: str | None = None) -> list[LoraJob]:
        conn = self._open()
        if status:
            rows = conn.execute(
                "SELECT * FROM lora_jobs WHERE status = ? ORDER BY created_at DESC", (status,)
            ).fetchall()
        else:
            rows = conn.execute("SELECT * FROM lora_jobs ORDER BY created_at DESC").fetchall()
        conn.close()
        return [self._row_to_job(dict(r)) for r in rows]

    def summary(self) -> dict[str, Any]:
        conn = self._open()
        rows = conn.execute(
            "SELECT status, COUNT(*) as n FROM lora_jobs GROUP BY status"
        ).fetchall()
        conn.close()
        return {r["status"]: r["n"] for r in rows}

    # ------------------------------------------------------------------
    # Internals
    # ------------------------------------------------------------------

    def _write_axolotl_config(self, job: LoraJob, config_dir: Path, output_dir: Path) -> Path:
        now = datetime.now(timezone.utc).isoformat()
        cfg = job.config
        content = _AXOLOTL_TEMPLATE.format(
            timestamp=now,
            base_model=job.base_model,
            data_path=job.data_path,
            dataset_type=cfg.get("dataset_type", "sharegpt"),
            output_dir=str(output_dir),
            use_4bit=str(cfg.get("use_4bit", True)).lower(),
            max_seq_length=cfg.get("max_seq_length", 2048),
            lora_r=cfg.get("lora_r", 16),
            lora_alpha=cfg.get("lora_alpha", 32),
            lora_dropout=cfg.get("lora_dropout", 0.05),
            gradient_accumulation_steps=cfg.get("gradient_accumulation_steps", 4),
            per_device_train_batch_size=cfg.get("per_device_train_batch_size", 2),
            num_train_epochs=cfg.get("num_train_epochs", 3),
            learning_rate=cfg.get("learning_rate", 2e-4),
            bf16=str(cfg.get("bf16", True)).lower(),
            fp16=str(cfg.get("fp16", False)).lower(),
            warmup_steps=cfg.get("warmup_steps", 10),
            output_logging_steps=cfg.get("output_logging_steps", 10),
        )
        path = config_dir / "axolotl_config.yaml"
        path.write_text(content)
        return path

    def _write_llamacpp_script(self, job: LoraJob, config_dir: Path, output_dir: Path) -> Path:
        script = (
            f"#!/bin/bash\n"
            f"# Jarvis LoraRunner — llama.cpp QLoRA\n"
            f"# Generated: {datetime.now(timezone.utc).isoformat()}\n\n"
            f"llama-finetune \\\n"
            f"  --model-base {job.base_model} \\\n"
            f"  --train-data {job.data_path} \\\n"
            f"  --output-dir {output_dir} \\\n"
            f"  --lora-r {job.config.get('lora_r', 16)} \\\n"
            f"  --lora-alpha {job.config.get('lora_alpha', 32)} \\\n"
            f"  --epochs {job.config.get('num_train_epochs', 3)} \\\n"
            f"  --batch {job.config.get('per_device_train_batch_size', 2)}\n"
        )
        path = config_dir / "finetune.sh"
        path.write_text(script)
        path.chmod(0o755)
        return path

    def _write_generic_config(self, job: LoraJob, config_dir: Path, output_dir: Path) -> Path:
        cfg = {**job.config, "base_model": job.base_model, "data_path": job.data_path,
               "output_dir": str(output_dir)}
        path = config_dir / "config.json"
        path.write_text(json.dumps(cfg, indent=2))
        return path

    def _build_launch_command(self, job: LoraJob, remote_host: str | None) -> list[str]:
        if job.backend == "axolotl":
            cmd = ["python", "-m", "axolotl.cli.train", job.config_path]
        elif job.backend == "llama.cpp":
            cmd = ["bash", job.config_path]
        elif job.backend == "unsloth":
            cmd = ["python", "-m", "unsloth.train", "--config", job.config_path]
        elif job.backend == "mlx-lm":
            cmd = ["python", "-m", "mlx_lm.lora", "--config", job.config_path]
        else:
            cmd = ["python", "-m", "axolotl.cli.train", job.config_path]

        if remote_host:
            ssh_host = remote_host or os.getenv("FORGE_TRAIN_HOST", "192.168.111.27")
            cmd = ["ssh", ssh_host] + cmd

        return cmd

    def _row_to_job(self, d: dict) -> LoraJob:
        return LoraJob(
            id=d["id"],
            name=d["name"],
            base_model=d["base_model"],
            backend=d["backend"],
            data_path=d["data_path"],
            status=d.get("status", "pending"),
            config_path=d.get("config_path") or "",
            adapter_path=d.get("adapter_path") or "",
            created_at=d.get("created_at") or "",
            started_at=d.get("started_at"),
            completed_at=d.get("completed_at"),
            final_loss=d.get("final_loss"),
            epochs_done=d.get("epochs_done") or 0,
            error=d.get("error"),
            config=json.loads(d.get("config_json") or "{}"),
        )

    def _save_job(self, job: LoraJob) -> None:
        conn = self._open()
        conn.execute(
            "INSERT OR REPLACE INTO lora_jobs"
            " (id, name, base_model, backend, data_path, status, created_at, config_json)"
            " VALUES (?, ?, ?, ?, ?, ?, ?, ?)",
            (job.id, job.name, job.base_model, job.backend, job.data_path,
             job.status, job.created_at, json.dumps(job.config)),
        )
        conn.commit()
        conn.close()

    def _set_error(self, job_id: str, error: str) -> None:
        conn = self._open()
        conn.execute(
            "UPDATE lora_jobs SET status = 'failed', error = ? WHERE id = ?", (error, job_id)
        )
        conn.commit()
        conn.close()

    def _set_completed(self, job_id: str, loss: float | None, adapter_path: str) -> None:
        now = datetime.now(timezone.utc).isoformat()
        conn = self._open()
        conn.execute(
            "UPDATE lora_jobs SET status='completed', completed_at=?, final_loss=?, adapter_path=?"
            " WHERE id=?",
            (now, loss, adapter_path, job_id),
        )
        conn.commit()
        conn.close()

    def _init_db(self) -> None:
        conn = self._open()
        conn.executescript(_DDL)
        conn.commit()
        conn.close()

    def _open(self) -> sqlite3.Connection:
        conn = sqlite3.connect(self._db, check_same_thread=False)
        conn.row_factory = sqlite3.Row
        return conn
